### PR TITLE
fastapi-template

### PR DESCRIPTION
**Pull request by Oluwaseun241**
FastAPI authentication template

### CODE REVIEW

**Comment by Oluwaseun241** [comment]
PS
I'm still trying to figure out the CLI function
@nmasi322 I would be glad if you can help put

**Comment by nmasi322** [comment]
Oh, you don’t need to worry about that.
When you’re done you can push to a different branch so I can test it.
Thank you so muchhhhhhhhh 🥹

**Comment by Oluwaseun241** [comment]
I can't create a branch here...create a testing branch from your side then I can make a PR to it

**Comment by nmasi322** [comment]
Done :)

**Pull request closed without merging**
